### ISSUE TITLE
EDI 850 support?

### ISSUE THREAD

**Issue by leosco** [tdecaluwe/node-edifact#30]
Does this support EDI 850? I'm receiving this error when I try to do a simple parse of a message:
```
Error: Invalid character * after reading segment name ISA
     at Object.invalidControlAfterSegment (/Users/leonidas/Projects/myProj/node_modules/edifact/parser.js:237:12)
     at Parser.write (/Users/leonidas/Projects/myProj/node_modules/edifact/parser.js:151:29)
```

**Comment by leosco** [comment]
Closing as EDI 850 is not supported by this project. I'll be publishing a repo soon that's capable of parsing EDI 850.
